Resources:
  FilesTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: filePK
          AttributeType: S
        - AttributeName: fileSK
          AttributeType: S
      BillingMode: PROVISIONED
      KeySchema: 
      - AttributeName: filePK
        KeyType: HASH
      - AttributeName: fileSK
        KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableClass: STANDARD
      TableName: files-table

